/**
 * Global function-word glossary. The reader resolves a tapped word via:
 * line.glosses → unit + earlier-unit vocab/phrases → this map.
 * Keys are lowercased, punctuation-stripped.
 */
export const GLOBAL_GLOSSES: Record<string, string> = {
  die: "the",
  "'n": "a / an",
  n: "a / an",
  se: "'s (possessive)",
  is: "is / am / are",
  was: "was / were",
  het: "have / has (also past-tense helper)",
  sal: "will",
  wil: "want to",
  kan: "can",
  moet: "must",
  mag: "may",
  word: "become / is being",
  wees: "to be",
  om: "to / in order to",
  te: "to",
  nie: "not",
  en: "and",
  maar: "but",
  of: "or",
  want: "because",
  dat: "that",
  as: "if / when / as",
  toe: "when (past) / then",
  dan: "then",
  so: "so",
  ook: "also",
  nog: "still / another",
  al: "already",
  net: "just / only",
  baie: "very / many",
  meer: "more",
  min: "little / few",
  ek: "I",
  my: "my / me",
  jy: "you",
  jou: "your / you",
  u: "you (formal)",
  hy: "he",
  hom: "him",
  sy: "she / his",
  haar: "her",
  dit: "it",
  ons: "we / us / our",
  julle: "you (plural)",
  hulle: "they / them / their",
  wat: "what / that / which",
  wie: "who",
  waar: "where",
  hoe: "how",
  wanneer: "when",
  hoekom: "why",
  waarom: "why",
  watter: "which",
  hier: "here",
  daar: "there",
  nou: "now",
  vandag: "today",
  gister: "yesterday",
  môre: "tomorrow / morning",
  in: "in",
  op: "on",
  by: "at / by",
  na: "to / after",
  van: "of / from",
  vir: "for",
  met: "with",
  aan: "on / to",
  uit: "out / from",
  oor: "over / about",
  onder: "under",
  tussen: "between",
  deur: "through / door",
  sonder: "without",
  teen: "against / at",
  tot: "until / to",
  af: "down / off",
  weg: "away",
  terug: "back",
  hierdie: "this / these",
  daardie: "that / those",
  elke: "every",
  iets: "something",
  niks: "nothing",
  iemand: "someone",
  niemand: "nobody",
  alles: "everything",
  almal: "everyone",
  ander: "other",
  self: "self",
  een: "one",
  twee: "two",
  drie: "three",
  ja: "yes",
  nee: "no",
  asseblief: "please",
  dankie: "thank you",
  meneer: "sir / Mr",
  mevrou: "madam / Mrs",
  gaan: "go / going to",
  kom: "come",
  sê: "say",
  doen: "do",
  maak: "make / do",
  kry: "get / receive",
  laat: "let / late",
  moenie: "don't (command)",
  geen: "no / none",
  gewees: "been",
  gehad: "had",
  hoef: "need (to)",
  sou: "would",
  gou: "quickly",
  weer: "again / weather",
  dus: "therefore",
  darem: "at least / really",
  mos: "as you know",
  sommer: "just / simply",
  glad: "at all / smooth",
  regtig: "really",
  seker: "sure / probably",
  miskien: "maybe",
  altyd: "always",
  nooit: "never",
  dikwels: "often",
  soms: "sometimes",
  vandaan: "from (a place)",
  daarna: "after that",
  eers: "first / only then",
  klaar: "finished",
  bietjie: "a little",
  lekker: "nice / tasty",
  goed: "good / well",
  reg: "right / correct",
  oukei: "okay",
  o: "oh",
  ai: "oh dear",
  sjoe: "wow / phew",
  eish: "eish (oh my)",
  hoor: "hear / okay? (tag)",
  né: "right? / isn't it?",
  afrikaans: "Afrikaans (the language)",
  engels: "English",
};

/**
 * People and place names used in dialogues (keys lowercased). Extend freely —
 * these carry no FSRS state.
 */
export const PROPER_NOUNS: Record<string, string> = {
  pieter: "(name)",
  thandi: "(name)",
  sipho: "(name)",
  anna: "(name)",
  jan: "(name)",
  marie: "(name)",
  lerato: "(name)",
  sarie: "(name)",
  piet: "(name)",
  botha: "(surname)",
  johan: "(name)",
  annelie: "(name)",
  kobus: "(name)",
  elsa: "(name)",
  zanele: "(name)",
  danie: "(name)",
  karin: "(name)",
  riaan: "(name)",
  nandi: "(name)",
  willem: "(name)",
  durban: "Durban (city)",
  kaapstad: "Cape Town",
  pretoria: "Pretoria (city)",
  johannesburg: "Johannesburg (city)",
  stellenbosch: "Stellenbosch (town)",
  bloemfontein: "Bloemfontein (city)",
  soweto: "Soweto (township)",
  "suid-afrika": "South Africa",
  amerika: "America",
  engeland: "England",
  karoo: "the Karoo (semi-desert region)",
  tafelberg: "Table Mountain",
  mei: "May",
  januarie: "January",
  februarie: "February",
  maart: "March",
  april: "April",
  junie: "June",
  julie: "July",
  augustus: "August",
  september: "September",
  oktober: "October",
  november: "November",
  desember: "December",
};
